In [2]:
import tensorflow as tf
import numpy as np
from IPython.display import Image

### tf.ones_like()

### tf.subtract()

> decision_p_comp = tf.subtract(tf.ones_like(decision_p), decision_p)

> 这一句计算出1-d

### tf.stack

In [3]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.stack([a, b], axis = 0)
d = tf.stack([a, b], axis = 1)
sess = tf.Session()
print(sess.run(c))
print(sess.run(d))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### tf.expand_dims

### tf.tile 

In [4]:
with tf.Graph().as_default():
    a = tf.constant([1,2],name='a') 
    b = tf.tile(a,[3])
    sess = tf.Session()
    print(sess.run(b))

[1 2 1 2 1 2]


### tf.reduce_mean

In [5]:
x = tf.constant([[1., 1.], [2., 2.]])
tf.reduce_mean(x)  # 1.5
tf.reduce_mean(x, 0)  # [1.5, 1.5]
tf.reduce_mean(x, 1)  # [1.,  2.]

<tf.Tensor 'Mean_2:0' shape=(2,) dtype=float32>

### tf.nn.dropout

### tf.gather